# RAG Fusion Factory Default Configuration

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 1
  reload: false

# Search Engine Configuration
search:
  timeout: 30.0
  max_concurrent_engines: 10
  retry_attempts: 3
  retry_delay: 1.0

# Model Configuration
model:
  cache_dir: "./models"
  auto_save: true
  version_control: true
  
  # XGBoost Configuration
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42
    n_jobs: -1
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0

# Normalization Configuration
normalization:
  default_method: "min_max"  # Options: min_max, z_score, quantile
  outlier_threshold: 2.5
  clip_values: true
  per_engine_params: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: false
  log_file: "logs/rag_fusion_factory.log"
  max_file_size: "10MB"
  backup_count: 5

# Training Configuration
training:
  batch_size: 32
  validation_split: 0.2
  max_epochs: 100
  early_stopping_patience: 10
  learning_rate: 0.001
  
  # Contrastive Learning
  contrastive_learning:
    margin: 1.0
    temperature: 0.1
    negative_sampling_ratio: 5
    loss_function: "triplet"  # Options: triplet, contrastive, ranking

# Hyperparameter Optimization
hyperparameter_optimization:
  enabled: true
  method: "bayesian"  # Options: grid, random, bayesian
  max_trials: 50
  timeout: 3600  # seconds
  
  # Search spaces
  search_space:
    xgboost:
      n_estimators: [50, 100, 200, 300]
      max_depth: [3, 6, 9, 12]
      learning_rate: [0.01, 0.1, 0.2, 0.3]
      subsample: [0.8, 0.9, 1.0]
    
    normalization:
      method: ["min_max", "z_score", "quantile"]
      outlier_threshold: [2.0, 2.5, 3.0]
    
    contrastive_learning:
      margin: [0.5, 1.0, 1.5, 2.0]
      temperature: [0.05, 0.1, 0.2, 0.3]
      negative_sampling_ratio: [3, 5, 7, 10]

# Performance Monitoring
monitoring:
  enabled: true
  metrics_collection_interval: 60  # seconds
  performance_tracking: true
  memory_profiling: false
  
# Circuit Breaker Configuration
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 30
  expected_exception_types: ["TimeoutError", "ConnectionError"]