# Default configuration for RAG Fusion Factory
# This configuration uses mock adapters by default
# Users should override this with their own configuration pointing to external search engines

logging:
  level: INFO
  format: json

# Default engines - using mock adapters for immediate functionality
# Users should replace these with their actual search engine configurations
engines:
  - engine_type: mock_inmemory
    engine_id: default_mock_1
    timeout: 5.0
    config:
      response_delay: 0.1
      failure_rate: 0.0
      max_results: 10
      documents:
        - id: welcome_1
          title: "Welcome to RAG Fusion Factory"
          content: "RAG Fusion Factory is a system for combining multiple search engines to improve retrieval quality. Configure your own search engines by editing the configuration file."
          category: "system"
          tags: ["welcome", "introduction"]
        
        - id: config_1
          title: "Configuration Guide"
          content: "To configure your search engines, edit the engines section in your configuration file. Supported engines include Elasticsearch, Solr, OpenSearch, and custom REST APIs."
          category: "documentation"
          tags: ["configuration", "setup"]
        
        - id: example_1
          title: "Example Search Document"
          content: "This is an example document to demonstrate search functionality. Replace the mock adapters with your actual search engine configurations."
          category: "example"
          tags: ["example", "demo"]

  - engine_type: mock_inmemory
    engine_id: default_mock_2
    timeout: 5.0
    config:
      response_delay: 0.15
      failure_rate: 0.0
      max_results: 8
      documents:
        - id: adapter_1
          title: "Available Adapters"
          content: "RAG Fusion Factory supports Elasticsearch, Solr, OpenSearch, database adapters, REST API adapters, and custom implementations."
          category: "adapters"
          tags: ["adapters", "engines"]
        
        - id: fusion_1
          title: "Fusion Strategies"
          content: "The system combines results from multiple search engines using various fusion strategies to improve overall search quality and coverage."
          category: "fusion"
          tags: ["fusion", "ranking"]

# Fusion configuration
fusion:
  default_limit: 10
  max_limit: 100
  timeout: 30.0
  
# Monitoring configuration
monitoring:
  enabled: true
  health_check_interval: 30
  metrics_collection: true