# Production Environment Configuration
# This file overrides default.yaml settings for production

api:
  debug: false
  workers: 4
  reload: false

search:
  max_concurrent_engines: 20
  timeout: 60.0

model:
  xgboost:
    n_estimators: 300
    n_jobs: -1

logging:
  level: "WARNING"
  file_logging: true
  log_file: "/var/log/rag_fusion_factory/app.log"

training:
  batch_size: 64
  max_epochs: 200

hyperparameter_optimization:
  max_trials: 100
  timeout: 7200  # 2 hours

monitoring:
  enabled: true
  metrics_collection_interval: 30

circuit_breaker:
  failure_threshold: 3
  recovery_timeout: 60